# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
      - image: mysql:5.7
        environment:
          - MYSQL_HOST=jdbc:mysql://localhost:3306/todolist
          - MYSQL_ROOT_PASSWORD=admin
          - MYSQL_USER=spring
          - MYSQL_PASSWORD=spring123
          - MYSQL_DATABASE=todolist
          - MYSQL_ROOT_HOST=%
          - DB_HOST=127.0.0.1
          - DB_PORT=3306
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew wrapper --gradle-version=7.1.1 --distribution-type=bin
      - run: ./gradlew tasks
      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run:
          name: Running test
          command: ./gradlew test

      # Upload test coverage
      - run:
          name: Generate test coverage
          command: ./gradlew jacocoTestReport

      # Upload test coverage
      - run:
          name: Upload test coverage
          command: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"